export const CAPSULE_ALL_DATA = "CAPSULE_ALL_DATA";
export const CAPSULE_ALL_DATA_LOADING = "CAPSULE_ALL_DATA_LOADING";
export const CAPSULE_ALL_DATA_ERR = "CAPSULE_ALL_DATA_ERR";

export const CAPSULE_SINGLE_DATA = "CAPSULE_SINGLE_DATA";
export const CAPSULE_SINGLE_DATA_LOADING = "CAPSULE_SINGLE_DATA_LOADING";
export const CAPSULE_SINGLE_DATA_ERR = "CAPSULE_SINGLE_DATA_ERR";


export const SET_CAPSULE_SERIAL = "SET_CAPSULE_SERIAL";
export const SET_CAPSULE_TYPE_FILTER = "SET_CAPSULE_TYPE_FILTER";
export const SET_CAPSULE_STATUS_FILTER = "SET_CAPSULE_STATUS_FILTER";
export const SET_CAPSULE_ORIGINAL_LAUNCH_FILTER = "SET_CAPSULE_ORIGINAL_LAUNCH_FILTER";

export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";




