export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_LOADING ="LOGIN_LOADING";
export const LOGIN_ERR ="LOGIN_ERR";
export const LOG_OUT ="LOG_OUT";


export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const REGISTER_NEW_USER_LOADING = "REGISTER_NEW_USER_LOADING";
export const REGISTER_NEW_USER_ERR = "REGISTER_NEW_USER_ERR";


export const GET_ALL_USERS = "GET_ALL_USERS";

export const SET_LOGIN_ERR_MESSAGE = "SET_LOGIN_ERR_MESSAGE";


